Fix bug #86
Boeing/config-file-validator pull request #93
Opened 2023-11-20 20:43 UTC by levkush

2023-11-20 22:32 UTC, kehoecj commented
Thanks for the PR @levkush - I need to test this on my Arch environment. If everything looks good I'll approve and will merge

2023-11-30 14:53 UTC, kehoecj requested changes

2023-12-11 15:15 UTC, kehoecj commented on PKGBUILD
@levkush Reminder for the following requested changes to get this MR approved and merged

2023-12-11 18:49 UTC, levkush commented on PKGBUILD
I added the required changes.

2023-12-11 18:59 UTC, kehoecj approved these changes
LGTM! Thanks for the PR

2023-12-11 19:01 UTC, merged